algoritmo "Estruturas de repetição"
// Função :
// Autor :
// Data : 23/06/2019
// Seção de Declarações 
var
valor   : inteiro
contador: inteiro
salto   : inteiro
inicio
// Seção de Comandos
contador <- 0

escreval("QUER CONTAR ATÉ QUANTO?")
leia (valor)
escreva ("Deseja pular de quanto em quanto?")
leia (salto)

enquanto (contador <= valor)faca
    escreva(contador)
    contador <- contador + salto
fimenquanto
fimalgoritmo
