algoritmo "Temperatura Conversão"
// Função :
// Autor :
// Data : 20/06/2019
// Seção de Declarações 
var

temp_atual: real
conversao_temp: real

inicio
// Seção de Comandos 

escreva ("Digite a temperatura atual em Fahrenheit: ")
        leia (temp_atual)
        conversao_temp <-((temp_atual - 32)/1.8)
        escreva ("A temperatura atual convertendo de FAHRENHEIT para GRAUS é IGUAL A: ",conversao_temp:4:1)
        
fimalgoritmo
