algoritmo "Idadecreuza"
// Função :
// Autor :
// Data : 20/06/2019
// Seção de Declarações 
var
   ano_atual      : inteiro
   ano_nascimento : inteiro
   idade          : inteiro
inicio
// Seção de Comandos

         Escreval ("Estamos em que ano? ")
         leia (ano_atual)
         Escreval ("Em que ano eu nasci? ")
         leia (ano_nascimento)
         idade <- (ano_atual - ano_nascimento)

         escreva ("Minha idade é: ",idade)
fimalgoritmo
